version: "3.8"

services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - zero_datav5:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
    networks:
      - adpwn_network

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - alpha_datav5:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0
    networks:
      - adpwn_network

  ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
    networks:
      - adpwn_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "adpwn"
      POSTGRES_USER: "adpwn"
      POSTGRES_PASSWORD: "adpwn"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - adpwn_network
    restart: on-failure

networks:
  adpwn_network:
    driver: bridge
    internal: true

volumes:
  zero_datav5:
  alpha_datav5:
  postgres_data: